export const urls = {
    // 登录
    login: "/user/login",
    // 注册
    register: "/user/save",
    // 根据任务id获得任务
    getTaskById: "/task/get",
    // 根据任务类型id获得任务
    getTaskByTypeId: "/task/getAll",
    // 获取所有礼品信息
    getGifts: "/shop/getAllShop",
    // 获取所有礼品信息(过滤删除)
    getGiftsWithoutDelete: "/shop/getAllShopNoDelete",
    // 修改礼品信息
    updateGift: "/shop/update",
    // 获取用户信息
    getUserInfo: "/user/get",
    // 接受任务
    acceptTask: "/task/saveTaskOfUser",
    // 创建任务
    createTask: "/task/save",
    // 任务查询
    searchTask: "/task/findLike",
    // 更改用户信息
    updateUserInfo: "/user/update",
    // 兑换礼品
    exchangeGift: "/shop/saveShopOfUser",
    // 添加新礼品
    addGift: "/shop/save",
    // 删除礼品
    deleteGift: "/shop/deleteByShopId",
    // 获取已经接收的任务
    getUserTasks: "/task/getTaskByUserId",
    // 完成任务
    completeTask: "/task/seccessByTask",
    // 获取发布的任务
    getPostTasks: "/task/getTaskByAuthor",
    // 获取用户已兑礼品
    getUserGifts: "/shop/getShopOfUser"
}